
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'WSSRefresh_Example' do
  pod 'WSSRefresh', :path => '../'

  target 'WSSRefresh_Tests' do
    inherit! :search_paths

    
  end
end
